FROM airhacks/payara-configured
MAINTAINER Adam Bien, adam-bien.com
# For more information about ping see: https://github.com/AdamBien/ping/
ADD ../../../platform-examples/todo-example/todo-server-javaee/build/libs/todo-app.war ${DEPLOYMENT_DIR}
